<?php
require __DIR__ . '/config/db.php';
?>
<!doctype html>
<html>
<head><meta charset="utf-8"><title>Projek PAW - LMS</title>
<link rel="stylesheet" href="assets/css/style.css"></head>
<body>
<div class="container">
  <div class="topbar">
    <div class="brand">Projek PAW LMS</div>
    <div class="nav">
      <?php if (is_logged_in()): ?>
        <a href="dashboard.php" class="btn-outline">Dashboard</a>
        <a href="auth/logout.php" class="btn-outline">Logout</a>
      <?php else: ?>
        <a href="auth/login.php" class="btn">Login</a>
        <a href="auth/register.php" class="btn-outline">Register</a>
      <?php endif; ?>
    </div>
  </div>

  <div class="grid">
    <div>
      <div class="card">
        <h2>Selamat datang di Projek PAW LMS</h2>
        <p class="meta">Platform pembelajaran online untuk praktikum dan final project.</p>
        <p style="margin-top:12px;">Jelajahi kursus, daftar, dan mulai belajar.</p>
        <p style="margin-top:12px;"><a class="btn" href="courses/index.php">Jelajah Kursus</a></p>
      </div>

      <div class="card">
        <h3>Kenapa menggunakan platform ini?</h3>
        <ul style="margin-top:10px;color:#555;">
          <li>Multi-role: Admin, Instructor, Student</li>
          <li>Materi, Kuis, Sertifikat</li>
          <li>Desain responsif & sederhana</li>
        </ul>
      </div>
    </div>

    <aside>
      <div class="card">
        <h4>Kontak</h4>
        <p class="meta">Email: admin@example.com</p>
      </div>
    </aside>
  </div>

  <div class="footer">Projek PAW — Generated by assistant</div>
</div>
</body>
</html>
